on:
  push:
    branches:
      - fixreadme

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          install.packages("devtools")
          install.packages("remotes")
          install.packages("pkgdown")
          install.packages("vdiffr")
          install.packages("textshaping", type = "binary")
          remotes::install_github("lorenzwalthert/gitsum")
          install.packages("ggthemes")
          remotes::install_deps(dependencies = TRUE)
          gitsum::parse_log_detailed()
        shell: Rscript {0}


